GAMMA_PREFIX=/home/dmlb2000/svn-repos/gamma/install

CPPFLAGS=-I$(GAMMA_PREFIX)/include/gamma-4.3.2 -g -pg -Wall
LDFLAGS=-L$(GAMMA_PREFIX)/lib/gamma-4.3.2 -Wl,-rpath=$(GAMMA_PREFIX)/lib/gamma-4.3.2 -lgamma -lm

